<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<title>www.fitness4.me - Workouts</title>
<meta charset="utf-8">
	<meta name="description" content="Premium HTML5 Template" />
	<?php if($this->defaultLang == 1){?>
	<meta name="keywords" content="wellness,Weightloss,diet,Exercise,Body building,workout,shape,training,gym,fitness app,online fitness,nutrition,10 minute workout,ten minute workout,quick workout,quick weight loss,lose weight,burn fat,fitness4.me,www.fitness4.me,fitness,sport,athletic" />	
	<?php }else { ?>
	<meta name="keywords" content="fitness4.me, www.fitness4.me, fitness,sport,athletic,wellness,Abnehmen,Diät,Training,Body Building,fitness app,online fitness" />
	<?php } ?>	
	<style>
input[type=range]:first-of-type {
  width: 200px;
}
</style>
	<link media="all" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/green-style.css">
	<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Merriweather:300' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/public/datepicker/jsDatePick_ltr.min.css" />
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/new/js/jquery-1.7.1.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/new/js/main.js"></script>
	<script  src="<?php echo $this->baseUrl();?>/public/js/frontend_validations.js"></script>
	<script src="https://github.com/fryn/html5slider/raw/master/html5slider.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/datepicker/jsDatePick.min.1.3.js"></script>
	
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/css/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>
  <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/fancybox/source/jquery.fancybox.css?v=2.0.6" type="text/css" media="screen" />
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/css/fancybox/source/jquery.fancybox.pack.js?v=2.0.6"></script>
  <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/fancybox/source/helpers/jquery.fancybox-buttons.css?v=1.0.2" type="text/css" media="screen" />
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/css/fancybox/source/helpers/jquery.fancybox-buttons.js?v=1.0.2"></script>
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/css/fancybox/source/helpers/jquery.fancybox-media.js?v=1.0.0"></script>
  <link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/fancybox/source/helpers/jquery.fancybox-thumbs.css?v=2.0.6" type="text/css" media="screen" />
  <script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/css/fancybox/source/helpers/jquery.fancybox-thumbs.js?v=2.0.6"></script>
	<script type="text/javascript">
	jQuery.noConflict();
  	jQuery(document).ready(function() {
    	jQuery(".text-overlay").fancybox({
    		helpers : {
            overlay : {
                opacity: 0.8,
                css : {
                    'background-color' : '#000'
                }
            }
        },

    		maxWidth	: 900,
    		maxHeight	: 380,
    		fitToView	: false,
    		width		: 650,
    		height		: 400,
    		autoSize	: false,
    		closeClick	: false,
    		openEffect	: 'none',
    		closeEffect	: 'none'
    	});
    });
  </script>
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34864449-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
<?php 
//get the current action and controller to redifrcet after language change
//echo $_SERVER['REQUEST_URI'];
 $currentPage        =  Zend_Controller_Front::getInstance()->getRequest()->getActionName(); 
 $currentController  =  Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
 
 ?>
	<div id="wrapper">
		<div class="w1">
			<div class="w2">
				<!-- header -->
				<header id="header">
					
					<!-- logo -->
					<h1 class="logo"><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'home'), $name = null, $reset = true);?>">www.fitness4.me</a></h1>
					
					<div id="flags">
						
					<a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'setlanguage'), $name = null, $reset = true);?>/lang/en/page/<?php echo $currentPage; ?>/contr/<?php echo $currentController; ?>"><img src="<?php echo $this->baseUrl();?>/public/latest/images/lang/en.png" alt="english" class="right-space" width="24" height="24" /></a>
<a href="<?php echo $this->url(array('controller'=>'index','action'=>'setlanguage'), $name = null, $reset = true);?>/lang/de/page/<?php echo $currentPage; ?>/contr/<?php echo $currentController; ?>"><img src="<?php echo $this->baseUrl();?>/public/latest/images/lang/de.png" alt="german"  width="24" height="24" /></a>
</div>
						<!-- main nav -->
						<nav id="nav">
							<ul>
							<?php if($this->loginStatus == 1){?>
							<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'homepage'), $name = null, $reset = true);?>"><?php echo $this->translate("About fitness4.me");?></a>
							<ul>	
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'homepage'), $name = null, $reset = true);?>"><?php echo $this->translate("What can we do for you?");?></a></li>
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'workhow'), $name = null, $reset = true);?>"><?php echo $this->translate("How does it work");?>?</a></li>
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'truth'), $name = null, $reset = true);?>"><?php echo $this->translate("The truth");?></a></li>

									</ul>			
										
										
										</li>
										<?php } else { ?>
										
									<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'homepage'), $name = null, $reset = true);?>"><?php echo $this->translate("What can we do for you?");?></a></li>
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'workhow'), $name = null, $reset = true);?>"><?php echo $this->translate("How does it work");?>?</a></li>
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'truth'), $name = null, $reset = true);?>"><?php echo $this->translate("The truth");?></a></li>	
										
										<?php } ?>
										
										
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'faq'), $name = null, $reset = true);?>"><?php echo $this->translate("FAQs");?></a></li>			
							<?php if($this->loginStatus == 1){?>
    							<li><a href="<?php echo $this->url(array('controller'=>'user',
                                        'action'=>'listworkouts'), $name = null, $reset = true);?>"><?php echo $this->translate("Workouts");?></a></li>
										
									<li><a href="<?php echo $this->url(array('controller'=>'user',
                                        'action'=>'settings'), $name = null, $reset = true);?>"><?php echo $this->translate("Settings");?></a></li>	
										
										<?php } ?>
							
							
							<li>
							<?php if($this->loginStatus == 1){?>
							<a href="<?php echo $this->url(array('controller'=>'user',
                                        'action'=>'logout'), $name = null, $reset = true);?>"><?php echo $this->translate("Logout");?></a>
                                        <?php }else { ?>
							<a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'login'));?>"><?php echo $this->translate("Login");?></a></li>
                                        <?php } ?>
						</ul>
						</nav>
				</header>
				<!-- main -->
				<div id="main">
					<!-- intro -->
					<div class="headline solid"></div>
					<div class="main-holder">
						<!-- content -->
						<?php  echo $this->layout()->content; ?>
								

							


						
						<!-- sidebar -->
						<aside class="col" id="sidebar">
						
							<?php echo $this->render('user/viewstats.phtml') ;?>
							
						</aside>
					</div>
				</div>
			</div>
	    	<!-- footer -->
			<footer id="footer">
				<div class="footer-holder">
					<?php echo $this->render('index/footer.phtml') ;?>
				</div>
			</footer>
		</div>
	</div>
</body>
</html>
<script type="text/javascript">
	window.onload = function(){
		new JsDatePick({
			useMode:2,
			target:"inputField",
			 selectedDate:{
	            year:1980,
	            month:1,
	            day:1
	       	      },
		    yearsRange: new Array(1940,2009),
			dateFormat:"%d-%m-%Y"

		});
	};
</script>
