<!DOCTYPE html>
<head>
	<?php echo $this->render('index/header.phtml') ;?>
</head>
<body>
<?php
//get the current action and controller to redifrcet after language change
//echo $_SERVER['REQUEST_URI'];
 $currentPage        =  Zend_Controller_Front::getInstance()->getRequest()->getActionName();
 $currentController  =  Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
 $currentParams      = Zend_Controller_Front::getInstance()->getRequest()->getParams();
 $paramsStr="";
 foreach($currentParams as $key => $value)
 {
 	if($key <> "module" && $key <> "controller" && $key <> "action")
                    $paramsStr .= $key . "," . $value . ",";
 }

 ?>
	<div id="wrapper">
		<div class="w1">
			<div class="w2">
				<!-- header -->
				<header id="header">
					<div class="line"></div>
					<!-- logo -->
				  	<!-- logo -->
  				<h1 class="logo"><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'home'), $name = null, $reset = true);?>">www.fitness4.me</a></h1>
  				<div id="flags">
						
					<a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'setlanguage'), $name = null, $reset = true);?>/lang/en/page/<?php echo $currentPage; ?>/contr/<?php echo $currentController; ?>"><img src="<?php echo $this->baseUrl();?>/public/latest/images/lang/en.png" alt="english" class="right-space" width="24" height="24" /></a>
<a href="<?php echo $this->url(array('controller'=>'index','action'=>'setlanguage'), $name = null, $reset = true);?>/lang/de/page/<?php echo $currentPage; ?>/contr/<?php echo $currentController; ?>"><img src="<?php echo $this->baseUrl();?>/public/latest/images/lang/de.png" alt="german"  width="24" height="24" /></a>
</div>
  					<nav id="nav">
  								<ul>
								<?php if($this->loginStatus == 1){?>
							<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'homepage'), $name = null, $reset = true);?>"><?php echo $this->translate("About fitness4.me");?></a>
							<ul>	
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'homepage'), $name = null, $reset = true);?>"><?php echo $this->translate("What can we do for you?");?></a></li>
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'workhow'), $name = null, $reset = true);?>"><?php echo $this->translate("How does it work");?>?</a></li>
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'truth'), $name = null, $reset = true);?>"><?php echo $this->translate("The truth");?></a></li>

									</ul>			
										
										
										</li>
										<?php } else { ?>
										
									<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'homepage'), $name = null, $reset = true);?>"><?php echo $this->translate("What can we do for you?");?></a></li>
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'workhow'), $name = null, $reset = true);?>"><?php echo $this->translate("How does it work");?>?</a></li>
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'truth'), $name = null, $reset = true);?>"><?php echo $this->translate("The truth");?></a></li>	
										
										<?php } ?>
										
										
										
										
										<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'faq'), $name = null, $reset = true);?>"><?php echo $this->translate("FAQs");?></a></li>			
							<?php if($this->loginStatus == 1){?>
    							<li><a href="<?php echo $this->url(array('controller'=>'user',
                                        'action'=>'listworkouts'), $name = null, $reset = true);?>"><?php echo $this->translate("Workouts");?></a></li>
										
									<li><a href="<?php echo $this->url(array('controller'=>'user',
                                        'action'=>'settings'), $name = null, $reset = true);?>"><?php echo $this->translate("Settings");?></a></li>	
										
										<?php } ?>
							
							
							<li>
							<?php if($this->loginStatus == 1){?>
							<a href="<?php echo $this->url(array('controller'=>'user',
                                        'action'=>'logout'), $name = null, $reset = true);?>"><?php echo $this->translate("Logout");?></a>
                                        <?php }else { ?>
							<a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'login'));?>"><?php echo $this->translate("Login");?></a></li>
                                        <?php } ?>
						</ul>
  					</nav>
  				</header>
					<!-- main -->
				<div id="main-login">
					<!-- intro -->
										
						<div class="container">
							
								<article class="col-12-first">
									<img class="login-pic"  src="<?php echo $this->baseUrl();?>/public/latest/images/home/slider/1.jpg" alt="login" >
								</article>
								<article class="col-12">
								
								
								<div id="box_bg">
								<div id="content-login">
								 <?php  echo $this->layout()->content; ?>


                               
								
							</article>

						</div>
						
						
						<!-- info-columns -->
						<section class="info-columns">
							<!-- info-item -->
							<div class="container">
								
								
							</div>
						</section>
						
					
				</div>										
			</div>
	    	<!-- footer -->
  			<footer id="footer">
  				<div class="footer-holder">
  					<?php echo $this->render('index/footer.phtml') ;?>
  				</div>
  			</footer>
  		</div>
  	</div>
	
</body>
</html>
<script type="text/javascript">
	window.onload = function(){
		new JsDatePick({
			useMode:2,
			target:"inputField",
			 selectedDate:{
	            year:1980,
	            month:1,
	            day:1
	       	      },
		    yearsRange: new Array(1940,2009),
			dateFormat:"%d-%m-%Y"

		});
	};
</script>