
<p><?php if($this->message){echo $this->message;} ?></p>
<p><?php if($this->captchaerror){echo $this->captchaerror;} ?></p>


<!--<form name="contactform" action="" method="POST" onsubmit="return validateContactForm();">
<p><label style="width:100px;float:left;"><?php echo $this->translate("Name");?>  *</label> <input type="text" name="name"></p>
<p><label style="width:100px;float:left;"><?php echo $this->translate("Email");?> *</label><input type="text" name="email"></p>
<p><label style="width:100px;float:left;"><?php echo $this->translate("Phone");?></label> <input type="text" name="phone"></p>

<p><label style="width:100px;float:left;"><?php echo $this->translate("Website");?></label> <input type="text" name="website"></p>

<p><label style="width:100px;float:left;"><?php echo $this->translate("Priority");?></label>
<select name="priority" size="1">
<option value="Low"><?php echo $this->translate("Low");?></option>
<option value="Normal"><?php echo $this->translate("Normal");?></option>
<option value="High"><?php echo $this->translate("High");?></option>
<option value="Emergency"><?php echo $this->translate("Emergency");?></option>
</select>
</p>

<p><label style="width:100px;float:left;"><?php echo $this->translate("Type");?></label>
<select name="type" size="1">

<option value="change"><?php echo $this->translate("Information Change");?></option>
<option value="addition"><?php echo $this->translate("Information Addition");?></option>
<option value="update"><?php echo $this->translate("Website Issues");?></option>
</select>
</p>

<p><label style="width:100px;float:left;"><?php echo $this->translate("Message");?>*</label><textarea name="message" rows="6" cols="35"></textarea></p>
<p><input type="submit" value="Send"><input type="reset" value="Clear"></p>
</form>-->
