<div>
change language <a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'setlanguage'));?>/lang/en">English</a> | <a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'setlanguage'));?>/lang/de">German</a>
</div>

<div>
<?php echo $this->pageTitle ;?>
</div>
<div><?php echo  $this->translate('Welcome User'); ?></div>


