<!DOCTYPE html>
<head>
	<meta charset="utf-8">
	<title>www.fitness4.me - Home</title>
	<meta name="description" content="Premium HTML5 Template" />
	<meta name="keywords" content="html5, css, xml, slider, blog, portfolio, business, corporate" />	
	<link media="all" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/new/css/green-style.css">
	<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Merriweather:300' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/new/css/carousel.css">
	
	</head>
	<body>
<div id="wrapper" style="background:#fff;width:600px;">
		
				<!-- header -->
				<header id="header">
					<div class="line"></div>
					<!-- logo -->
					<h1 class="logo"><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'home'), $name = null, $reset = true);?>">www.fitness4.me</a></h1>
										</header>

<div id="main" style="width:500px;">

<h3><?php echo $this->pageTitle ;?></h3>
<p><?php echo $this->pageContent ;?></p>



</div>
</div>
</body>
</html>

