<!-- tab-content -->
								<article class="tab-content2" id="tab-4">
									<h4>Video Intro</h4>
									<embed width='638' height='390' flashvars='file=http://2.s3.envato.com/files/4748801/Promote Your App or Service Preview V2.flv&skin=http://videohive.net/video_player/modieus.zip&image=http://3.s3.envato.com/files/4748799/Promote Your App or Service_In Line Image V2.jpg' wmode='transparent' src='http://videohive.net/video_player/player.swf' />
								</article>