<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta equiv="Content-Type" content="text/html;charset=utf-8" />
        <title><?php echo $this->escape($this->title);?></title>
        <link rel="stylesheet" type="text/css" media="screen"
              href="<?php echo $this->baseUrl();?>/public/admin/css/site.css" />
         <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/public/datepicker/jsDatePick_ltr.min.css" />      
        <script language="javascript" src="<?php echo $this->baseUrl();?>/public/js/workout_form_js.js"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.js"></script>
        <script language="javascript" src="<?php echo $this->baseUrl();?>/public/js/userinfo.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl();?>/library/ckeditor/ckeditor.js"></script>
		
		<script language="javascript" src="<?php echo $this->baseUrl();?>/public/admin/js/jquery-ui-1.7.1.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/datepicker/jsDatePick.min.1.3.js"></script>
<script type="text/javascript">
$(document).ready(function(){ 

	$(function() {
		$("#contentLeft ul").sortable({ opacity: 0.6, cursor: 'move', update: function() {
			var order = $(this).sortable("serialize") + '&action=updateRecordsListings';
			
			$.post('http://' + '<?php echo $_SERVER['SERVER_NAME'];?>' + ':' + '<?php echo $_SERVER['SERVER_PORT'];?>' + "/player/updateDB.php", order, function(theResponse){
				alert(theResponse);
			});
		}
		});
	});

});
</script>
        
       <script type="text/javascript">
	$(document).ready(function(){
		CKEDITOR.replace('editor1');
		CKEDITOR.replace('editor2');
		CKEDITOR.replace('editor3');
		CKEDITOR.replace('editor4');
	});
</script>
    </head>
    <?php $siteUrl            = 'http://'.$_SERVER['SERVER_NAME'].':'.$_SERVER['SERVER_PORT'] .$this->baseUrl(); ?>
    <body onload="ajax_getTime('<?php echo $siteUrl; ?>');">
        <div id="content">
       
            <h1><?php echo $this->escape($this->title);?></h1>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>
<script type="text/javascript">
	window.onload = function(){
		new JsDatePick({
			useMode:2,
			target:"inputField1",
			 selectedDate:{
	            year:2012,
	            month:8,
	            day:1
	       	      },
		    yearsRange: new Array(2012,2100),
			dateFormat:"%d-%m-%Y"

		});
	};
</script>