<meta charset="utf-8">
	<title>www.fitness4.me - FitnessWorkouts</title>
	<meta name="description" content="www.fitness4.me" />
	<?php if($this->defaultLang == 1){?>
	<meta name="keywords" content="fitness4.me, www.fitness4.me, fitness,sport,athletic,wellness,Weightloss,diet,Exercise,Body building,workout,shape,training,gym,fitness app,online fitness,nutrition,10 minute workout,ten minute workout,quick workout,quick weight loss,lose weight,burn fat,fitness4.me,www.fitness4.me,fitness,sport,athletic" />	
	<?php }else { ?>
	<meta name="keywords" content="fitness4.me, www.fitness4.me, fitness,sport,athletic,wellness,Abnehmen,Diät,Training,Body Building,fitness app,online fitness,wellness,Weightloss,diet,Exercise,Body building,workout,shape,training,gym,fitness app,online fitness,nutrition,10 minute workout,ten minute workout,quick workout,quick weight loss,lose weight,burn fat,fitness4.me,www.fitness4.me,fitness,sport,athletic" />
	<?php } ?>
	<link media="all" rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/green-style.css">
    <link href="<?php echo $this->baseUrl();?>/public/css/login.css" rel="stylesheet" type="text/css" />
	<link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:600' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Merriweather:300' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/public/datepicker/jsDatePick_ltr.min.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/public/css/carousel.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/js/nivo-slider/themes/default/default.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/js/nivo-slider/nivo-slider.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/js/nivo-slider/bar/bar.css" type="text/css" media="screen" />
	<style>
input[type=range]:first-of-type {
  width: 200px;
}
</style>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/new/js/jquery-1.7.1.min.js"></script>
	
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/js/nivo-slider/jquery.nivo.slider.js"></script>		
	<script type="text/javascript">
	$(window).load(function() {
		$('#slider').nivoSlider({
			effect: 'fade',
			slices: 8,
			boxCols: 7,
			boxRows: 5,
			animSpeed: 700,
			pauseTime: 7000,
			startSlide: 0,
			directionNav: true,
			directionNavHide: true,
			controlNav: true,
			controlNavThumbs: false,
			controlNavThumbsFromRel: false,
			controlNavThumbsSearch: '.jpg',
			controlNavThumbsReplace: '_thumb.jpg',
			keyboardNav: true,
			pauseOnHover: true,
			manualAdvance: false,
			captionOpacity: 0.8,
			prevText: 'Prev',
			nextText: 'Next',
			beforeChange: function(){},
			afterChange: function(){},
			slideshowEnd: function(){},
			lastSlide: function(){},
			afterLoad: function(){}
		});
	});
	</script>
	
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/tinybox/css/prettyPhoto.css" type="text/css" media="screen" />
	
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/new/js/main.js"></script>
	<script src="<?php echo $this->baseUrl();?>/public/tinybox/js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
	<script src="https://github.com/fryn/html5slider/raw/master/html5slider.js"></script>
	<script  src="<?php echo $this->baseUrl();?>/public/js/frontend_validations.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/datepicker/jsDatePick.min.1.3.js"></script>
	
	
	<!--[if IE 7]><link rel="stylesheet" type="text/css" href="css/ie.css"><![endif]-->
	<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34864449-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>