<p><?php include("admin_sidebar.phtml");?></p>
<div class="language_block">
<p><?php include("code_menu.phtml");?></p>
<form name="addCodes" method="POST" action="" enctype="multipart/form-data">
<table>
<tr><td>Promotion Code</td><td><input type="text" name="code_name" value=""></td></tr>
<tr><td>Reduction in price(please enter integer value without currency sign)</td><td><input type="text" name="price_reduction" value=""></td></tr>
<tr><td>Activate</td><td><input type="checkbox" name="code_status" value="1"></td></tr>

<tr><td colspan="2"><input type="submit" name="codeSubmit" value="Add Promotion Code" class="noWarn"></td></tr>
</table>


</form>
</div>