<p><?php include("exercise_menu.phtml");?></p>
<div class="language_block">
<?php include("interests_menu.phtml"); ?>
<form name="addInterest" method="POST" action="">
<table>
<tr><td>Interest Name</td><td><input type="text" name="interest_name" value=""></td></tr>

<tr><td colspan="2"><input type="submit" name="interestSubmit" value="Add Interest Name" class="noWarn"></td></tr>
</table>


</form>
</div>