
<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addcodes'), $name = null, $reset = true);?>">Add Promotion Code</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listcodes'), $name = null, $reset = true);?>">List Codes</a>
                                        


</p>
                                        
</div>