<p><?php include("exercise_menu.phtml");?></p>
<div class="language_block">
<?php include("interests_menu.phtml"); ?>
<form name="editinterest" method="POST" action="">
<table>

<tr><td>Interest Name</td><td><input type="text" name="interest_name" value="<?php echo $this->fitnessMultiIntData['interest_name']; ?>"></td></tr>
<tr><td><input type="hidden" name="langId" value="<?php echo $this->langId; ?>"></td></tr>
<tr><td><input type="hidden" name="intId" value="<?php echo $this->intId; ?>"></td></tr>
<tr><td colspan="2"><input type="submit" name="interestSubmit" value="Update Interest Name" class="noWarn"></td></tr>
</table>


</form>
</div>