<p><?php include("exercise_menu.phtml");?></p>
<div class="language_block">
<?php include("muscles_menu.phtml"); ?>
<form name="editMuscle" method="POST" action="">
<table>
<tr><td>Muscle Name</td><td><input type="text" name="muscle_name" value="<?php echo $this->fitnessMultiMuscleData['area_name']; ?>"></td></tr>
<tr><td><input type="hidden" name="langId" value="<?php echo $this->langId; ?>"></td></tr>
<tr><td><input type="hidden" name="areaId" value="<?php echo $this->areaId; ?>"></td></tr>
<tr><td colspan="2"><input type="submit" name="muscleSubmit" value="Update Muscle Name" class="noWarn"></td></tr>
</table>


</form>
</div>