<p><?php include("exercise_menu.phtml");?></p>
<div class="workout">
<p ><?php include("workout_menu.phtml");?></p>

<form method="POST" action="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'updateworkout'));?>" name="workoutForm" onsubmit="return validateWorkoutForm();" >
<table>
<tr><td>Exercise Name </td><td><input type="text" name="workout_name" value="<?php echo $this->workoutName['workout_name']; ?>"></td></tr>
<tr><td>Other Side?</td> <td>Yes <input type="radio" name="otherside" value="1" <?php if($this->workoutGeneralData['otherside']==1){echo "checked";}?>> No <input type="radio" name="otherside" value="0"></td></tr>

<tr><td>Primary Muscles</td>
<td>
<select name="primary_muscle">
<option value="">Select Primary Muscle</option>
<?php foreach($this->musclesList as $muscles)
{  ?>

<option value="<?php echo $muscles['area_id']; ?>" <?php if($muscles['area_id'] == $this->primary_muscle){echo "selected";} ?>><?php echo $muscles['area_name']; ?></option>
	
<?php } ?>
</select>
</td></tr>

<tr><td>Secondary Muscles</td>
<td>
<select name="secondary_muscle" multiple size="12">
<option value="">Select Secondary Muscle</option>
<?php
$k=1;
 foreach($this->musclesList as $muscles)
{  ?>

<option value="<?php echo $muscles['area_id']; ?>" <?php if(in_array($muscles['area_id'],$this->sec_muscle)){echo "selected";} ?>><?php echo $muscles['area_name']; ?></option>
	
<?php $k=$k+1;} ?>
</select>
</td></tr>
</table>
<table>
<tr><td>Yoga Preparation</td><td><textarea name="workout_preparation" cols="35" rows="8"><?php echo $this->workoutGeneralMultilang['workout_preparation']; ?></textarea> <br/><b>Preparation</b> : <?php echo $this->getGermanDescription['workout_preparation']; ?></td> </tr>
<tr><td>Yoga Caution</td><td><textarea name="workout_execution" cols="35" rows="8"><?php echo $this->workoutGeneralMultilang['workout_execution']; ?></textarea>
 <br/><b>Caution</b> : <?php echo $this->getGermanDescription['workout_execution']; ?></td></tr>
<tr><td>Yoga Beginner Tip</td><td><textarea name="workout_advice" cols="35" rows="8"><?php echo $this->workoutGeneralMultilang['workout_advice']; ?></textarea>
<br/><b>Beginner Tip</b> : <?php echo $this->getGermanDescription['workout_advice']; ?></td></tr>
</table>
<table>
<tr><td colspan="5">Equipment Required ?  Yes <input type="radio" name="equipment_required" value="1" <?php if($this->workoutEquipments['equipment_required'] == '1'){echo "checked";} ?>>   No <input type="radio" name="equipment_required" value="0" <?php if($this->workoutEquipments['equipment_required'] == '0'){echo "checked";} ?>></td></tr>
<tr><td>Equipment</td><td>Home</td><td>Nature</td><td>Hotel</td><td>Office</td></tr>
<?php 
$i=1;
foreach($this->equipmentList as $equipment)
{  ?>

<tr><td><?php echo $equipment['equipment_name']; ?></td><td><input type="checkbox" name="home" value="<?php echo $equipment['equipment_id']; ?>" <?php if(strstr($this->workoutEquipments['equipments_home'],$equipment['equipment_id'])){echo "checked";} ?>></td><td><input type="checkbox" name="nature" value="<?php echo $equipment['equipment_id']; ?>" <?php if(strstr($this->workoutEquipments['equipments_nature'],$equipment['equipment_id'])){echo "checked";} ?>></td>
<td><input type="checkbox" name="hotel" value="<?php echo $equipment['equipment_id']; ?>" <?php if(strstr($this->workoutEquipments['equipments_hotel'],$equipment['equipment_id'])){echo "checked";} ?>></td><td><input type="checkbox" name="office" value="<?php echo $equipment['equipment_id']; ?>" <?php if(strstr($this->workoutEquipments['equipments_office'],$equipment['equipment_id'])){echo "checked";} ?>></td></tr>
	
<?php $i=$i+1;
} ?>
<tr><td><input type="hidden" name="exerciseslist" value=""></td></tr>
<tr><td><input type="hidden" name="home_equipments" value=""></td></tr>
<tr><td><input type="hidden" name="nature_equipments" value=""></td></tr>
<tr><td><input type="hidden" name="hotel_equipments" value=""></td></tr>
<tr><td><input type="hidden" name="office_equipments" value=""></td></tr>
<tr><td><input type="hidden" name="sec_muscles" value=""></td></tr>
</table>
<table>
<tr><th colspan="3">Ranking</th></tr>
<tr>
<?php 
$fitnessRanking  = new FitnessExerciseRanking();

$k=0;
$d=1;
foreach($this->musclesList as $muscles)
{  
  $rankingDetail  =  $fitnessRanking->getRankingById($this->workoutID,$muscles['area_id']);
  $ranking        =  $rankingDetail["ranking"];
 
?>

<td style="width:200px;">
<?php echo $muscles['area_name']; ?><br/>
<select name="ranking_<?php echo $muscles['area_id']; ?>">
<option value=""></option>
<?php for($i=1;$i<=6;$i++) { 

	/*if($muscles['area_id'] == $this->workoutRanking[$k]['body_area_id'])
	{
		if($this->workoutRanking[$k]['ranking'] ==$i )
		{
			$selected = "selected";
		}
		else 
		{
			$selected = "";
		}
	}*/
	if($ranking == $i)
	{
		$selected = "selected";
	}
	else 
		{
			$selected = "";
		}
	?>
<option value="<?php echo $i;?>"  <?php echo $selected; ?>><?php echo $i;?></option>
<?php } ?>
</select>
<input type="hidden" name="rankID_<?php echo $muscles['area_id']; ?>" value="<?php echo $this->workoutRanking[$k]['ranking_id']; ?>">
</td>
<?php if(($d%8)== 0){echo "</tr><tr>";}?>
<?php $k=$k+1;


$d=$d+1;} ?>
</tr>
</table>
<table>
<tr><th colspan="3">Repetition</th></tr>

<tr><td>Beginners</td><td> <input type="checkbox" name="workout_level[]" value="1" <?php if(strstr($this->workoutGeneralData['workout_level'],"1")){echo "checked";} ?>> <input type="text" name="repetition_beginners" size="4" value="<?php echo $this->repetitionBeginner; ?>"></td><td>advanced</td><td> <input type="checkbox" name="workout_level[]" value="2" <?php if(strstr($this->workoutGeneralData['workout_level'],"2")){echo "checked";} ?>> <input type="text" size="4" name="repetition_advanced" value="<?php echo $this->repetitionAdvanced; ?>"></td><td>Expert</td><td> <input type="checkbox" name="workout_level[]" value="3" <?php if(strstr($this->workoutGeneralData['workout_level'],"3")){echo "checked";} ?>> <input type="text" size="4" name="repetition_professional" value="<?php echo $this->repetitionProfessn; ?>"></td></tr>

</table>

<table>
<tr><th colspan="3">Exercise Documents</th></tr>
<tr><td>WorkoutImage upload</td><td><a href="javascript:void(0);" onclick="myimagecrop('<?php echo $this->workoutID; ?>');"><img src="<?php echo $this->baseUrl;?>/public/images/upload.jpg" /></a>  <img src="<?php echo $this->baseUrl;?>/public/images/exercises/single/<?php echo $this->workoutGeneralData['workout_imagethumb'];?>" /></td></tr>
										<input type="hidden" name="croppedimage" value="">

<tr><td>Workout Youtube link</td><td><input type="text" name="youtube_link" value="<?php echo $this->workoutDocumentsMulti['workout_youtube_link']; ?>"></td></tr>
<tr><td>Workout Sound File</td><td><input type="text" name="sound_file" value="<?php echo $this->workoutDocumentsMulti['workout_sound_file']; ?>"></td></tr>
<tr><td>Workout video File</td><td><input type="text" name="video_file" value="<?php echo $this->workoutDocuments['workout_video_file']; ?>"></td></tr>
<tr><td>Workout poster File</td><td><input type="text" name="poster_video" value="<?php echo $this->workoutDocuments['poster_video']; ?>"></td></tr>
</table>

<table>
<tr><td colspan="2"><a href="javascript:void(0);" onclick="mypopup('<?php echo $this->workoutID; ?>');"><b>View Workouts</b></a></td></tr>
<tr><td>Duration of exercise(in seconds)</td>
<td>
<input type="text" name="timeframes" value="<?php echo $this->workoutGeneralData['workout_timeframe']; ?>" size="3">
</td>
</tr>
<tr><td>Free workout ?</td> <td>Yes <input type="radio" name="workout_pay_status" value="free" <?php if($this->workoutGeneralData['workout_pay_status'] == "free"){echo "checked";} ?>>   No <input type="radio" name="workout_pay_status" value="paid" <?php if($this->workoutGeneralData['workout_pay_status'] == "paid"){echo "checked";} ?>></td></tr>
<tr><td>Workout rate</td><td><input type="text" name="workout_rate" value="<?php echo $this->workoutGeneralData['workout_rate']; ?>"></td></tr>
<tr><td>Translator check</td><td><input type="checkbox" name="trans_check" value="1" <?php if($this->workoutGeneralData['translator_check']==1){echo "checked";} ?>></td></tr>
<tr><td>Master check</td><td><input type="checkbox" name="master_check"  value="1" <?php if($this->adminType == 2) echo "disabled";?> <?php if($this->workoutGeneralData['master_check']==1){echo "checked";} ?> checked="checked"></td></tr>
</table>
<input type="hidden" name="langID" value="<?php echo $this->langID;?>">
<input type="hidden" name="workoutID" value="<?php echo $this->workoutID;?>">
<input type="hidden" name="masterStatus" value="">
<input type="submit" name="submitWorkoutForm" value="Update Exercise" class="noWarn">
</form>
</div>

<script>
function mypopup(exerciseid)
{
	var left = (screen.width/2)-(600/2);
    var top = (screen.height/2)-(600/2);
    
    mywindow = window.open ('<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'viewworkouts'), $name = null, $reset = true);?>/exercise/'+exerciseid, 'mywindow','location=1,status=1,scrollbars=1, width=600,height=600,top='+top+', left='+left);
    
}

function myimagecrop(exerciseid)
{
	var left = (screen.width/2)-(600/2);
    var top = (screen.height/2)-(600/2);
    
    mywindow = window.open ('<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'cropimage'), $name = null, $reset = true);?>/exercise/'+exerciseid, 'mywindow','location=1,status=1,scrollbars=1, width=800,height=600,top='+top+', left='+left);
    
}
</script>