<p><?php include("admin_sidebar.phtml");?></p>
<div class="language_block">
<?php include("language_menu.phtml"); ?>
<form name="editLanguage" method="POST" action="" enctype="multipart/form-data">
<table>
<tr><td>Language Name(german,swedish etc)</td><td><input type="text" name="language_name" value="<?php echo $this->fitnessLanguageData['language_name']; ?>"></td></tr>
<tr><td>Language Code(de,se etc)</td><td><input type="text" name="language_code" value="<?php echo $this->fitnessLanguageData['language_code']; ?>"></td></tr>
<tr><td>Upload flag(60x60)</td><td><input type="file" name="language_flag"></td></tr>
<tr><td colspan="2"><image src="<?php echo $this->baseUrl();?>/public/images/languages/<?php echo $this->fitnessLanguageData['language_code']; ?>.png" /></td></tr>
<tr><td colspan="2"><input type="hidden" name="language_id" value="<?php echo $this->langauageId; ?>"></td></tr>
<tr><td colspan="2"><input type="submit" name="languageEditSubmit" value="Update Language" class="noWarn"></td></tr>
</table>


</form>
</div>