
<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addequipment'), $name = null, $reset = true);?>">Add Equipment</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listequipments'), $name = null, $reset = true);?>">List Equipments</a>
                                        


</p>
                                        
</div>