<div class="sidebar">
 <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'homeuser'), $name = null, $reset = true);?>">Home</a>
       
| <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listworkout'), $name = null, $reset = true);?>/active/1">List  Exercises</a>  
                                        
    | <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listworks'), $name = null, $reset = true);?>">Workout Management</a>  
                                        
    | <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listworkoutrates'), $name = null, $reset = true);?>">Workout Rates</a>                                      
                                                                              
 | <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listmuscles'), $name = null, $reset = true);?>">Body Muscles Management</a>
                                        
| <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listequipments'), $name = null, $reset = true);?>">Equipments Management</a>   
                                        
                                                                             
 | <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listinterests'), $name = null, $reset = true);?>">Interests Management</a>  
                                                                                                                     
  | <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listtargets'), $name = null, $reset = true);?>">Targets Management</a>                                         
                                        
</div>