
<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addinterest'), $name = null, $reset = true);?>">Add Interests</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listinterests'), $name = null, $reset = true);?>">List Interests</a>
                                        


</p>
                                        
</div>