
<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addlanguages'), $name = null, $reset = true);?>">Add Language</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listlanguages'), $name = null, $reset = true);?>">List Language</a>
                                        


</p>
                                        
</div>