<p><?php include("admin_sidebar.phtml");?></p>
<div class="language_block">
<?php include("pages_menu.phtml"); ?>
<table>
<tr><th>#</th><th>News</th><th>Translations</th><th>Remove</th></tr>
<?php 
$i=1;
foreach($this->newsData as $news)
{?>
<tr><td><?php echo $i;?></td><td><?php echo $news['news']; ?></td>
<td>
<?php foreach($this->languageList as $lang) { ?>
<a href="<?php echo $this->url(array('controller'=>'admin','action'=>'editnews'));?>/langId/<?php echo $lang['language_id']; ?>/newsId/<?php echo $news['id']; ?>"><image src="<?php echo $this->baseUrl();?>/public/images/languages/<?php echo $lang['language_code']; ?>.png" /></a>
<?php } ?>
</td>


<td><a href="javascript:void(0)" onclick="deletefun(<?php echo  $news["id"];?>);"><image src="<?php echo $this->baseUrl();?>/public/images/delete.jpg" /></a></td>
</tr>
<?php 

$i=$i+1;
} ?>

</table>



</div>
<script type="text/javascript">
function deletefun(val)
{
if(confirm("Do you want to delete this news?"))
{
window.location.href="<?php echo $this->baseUrl();?>/admin/removenews/delete/"+val;
return false;
}
else{
return false;
}
}
</script>