<p><?php include("exercise_menu.phtml");?></p>
<div class="workout_list">
<p ><?php include("workout_menu.phtml");?></p>

<table>
<tr><th>#</th><th>Exercise</th><th>Primary Muscles</th><th>Secondary Muscles</th><th>Beginners</th><th>Advanced</th><th>Professional</th><th>Edit</th><th>Languages</th></tr>
<?php
$i=1;
 foreach($this->workoutArray as $workout)  { ?>
<tr><td><?php echo $i;?></td><td><?php echo  $workout["workout_name"];?></td><td><?php echo  $workout["primaryMuscle"];?></td><td><?php echo  $workout["secondaryMuscle"];?></td>
<td><?php if(in_array("1",$workout["level"])) { echo "yes";}?></td><td><?php if(in_array("2",$workout["level"])) { echo "yes";}?></td><td><?php if(in_array("3",$workout["level"])) { echo "yes";}?></td>
<td> <a href="javascript:void(0)" onclick="deletefun(<?php echo  $workout["workout_id"];?>);"><image src="<?php echo $this->baseUrl();?>/public/images/delete.jpg" /></a></td>

<td>
<?php foreach($this->languageList as $lang) { ?>
<a href="<?php echo $this->url(array('controller'=>'admin','action'=>'editworkout'));?>/workoutId/<?php echo  $workout["workout_id"];?>/langId/<?php echo $lang['language_id']; ?>"><image src="<?php echo $this->baseUrl();?>/public/images/languages/<?php echo $lang['language_code']; ?>.png" /></a>
<?php } ?>
</td>
</tr>
<?php 
 
 $i=$i+1;} 
 ?>
</table>
</div>
<script type="text/javascript">
function deletefun(val)
{
if(confirm("Do you want to delete this workout?"))
{
window.location.href="<?php echo $this->baseUrl();?>/admin/workoutedit/delete/"+val;
return false;
}
else{
return false;
}
}
</script>