<p><?php include("exercise_menu.phtml");?></p>
<div class="language_block">
<?php include("equip_menu.phtml"); ?>
<table>
<tr><th>#</th><th>Equipment Name</th><th>Translations</th><th>Remove</th></tr>
<?php 
$i=1;
foreach($this->equipData as $equip)
{?>
<tr><td><?php echo $i;?></td><td><?php echo $equip['eqp_name']; ?></td>
<td>
<?php foreach($this->languageList as $lang) { ?>
<a href="<?php echo $this->url(array('controller'=>'admin','action'=>'editequipment'));?>/langId/<?php echo $lang['language_id']; ?>/equipId/<?php echo $equip['eqp_home_id']; ?>"><image src="<?php echo $this->baseUrl();?>/public/images/languages/<?php echo $lang['language_code']; ?>.png" /></a>
<?php } ?>
</td>


<td><a href="javascript:void(0)" onclick="deletefun(<?php echo  $equip["eqp_home_id"];?>);"><image src="<?php echo $this->baseUrl();?>/public/images/delete.jpg" /></a></td>

<?php 

$i=$i+1;
} ?>

</table>



</div>
<script type="text/javascript">
function deletefun(val)
{
if(confirm("Do you want to delete this equipment?"))
{
window.location.href="<?php echo $this->baseUrl();?>/admin/removeequipment/delete/"+val;
return false;
}
else{
return false;
}
}
</script>