<p><?php include("exercise_menu.phtml");?></p>
<div class="language_block">
<?php include("work_menu.phtml"); ?>
<table>
<tr><th>#</th><th>Workout Name</th><th>Edit</th><th>Remove</th></tr>
<?php 
$i=1;
foreach($this->workoutData as $work)
{?>
<tr><td><?php echo $i;?></td><td><?php echo $work['work_name']; ?></td>

<td><a href="<?php echo $this->url(array('controller'=>'admin','action'=>'editwork'));?>/workId/<?php echo  $work['id'];?>"><image src="<?php echo $this->baseUrl();?>/public/images/edit.jpg" /></a></td>

<td>
<?php foreach($this->languageList as $lang) { ?>
<a href="<?php echo $this->url(array('controller'=>'admin','action'=>'editwork'));?>/langId/<?php echo $lang['language_id']; ?>/workId/<?php echo $work['id']; ?>"><image src="<?php echo $this->baseUrl();?>/public/images/languages/<?php echo $lang['language_code']; ?>.png" /></a>
<?php } ?>
</td>


<td><a href="javascript:void(0)" onclick="deletefun(<?php echo  $work["id"];?>);"><image src="<?php echo $this->baseUrl();?>/public/images/delete.jpg" /></a></td>

<?php 

$i=$i+1;
} ?>

</table>



</div>
<script type="text/javascript">
function deletefun(val)
{
if(confirm("Do you want to delete this workout?"))
{
window.location.href="<?php echo $this->baseUrl();?>/admin/removework/delete/"+val;
return false;
}
else{
return false;
}
}
</script>