<p><?php include("admin_sidebar.phtml");?></p>
<div class="language_block">
<?php include("users_menu.phtml"); ?>
<table>
<tr><th><a href="<?php echo $this->url(array('controller'=>'admin','action'=>'listusersoffer'));?>">Offers</a></th><th><a href="<?php echo $this->url(array('controller'=>'admin','action'=>'listusersupdate'));?>">Updates</a></th><th><a href="<?php echo $this->url(array('controller'=>'admin','action'=>'listusersdnb'));?>">None</a></th></tr>

<tr><th>#</th><th>Name</th><th>Gender</th><th>Email</th><th>Level</th><th>More Info</th></tr>
<?php 
$i=1;
foreach($this->listUsers as $user)
{?>
<tr><td><?php echo $i;?></td><td><?php echo $user['user_first_name']." ".$user['user_surname']; ?></td><td><?php echo $user['user_gender']; ?></td>
<td><?php echo $user['user_email']; ?></td><td><?php if($user['user_workout_level'] == 1 ){echo "Beginner";}  if($user['user_workout_level'] == 2 ){echo "Advanced";} if($user['user_workout_level'] == 3 ){echo "Professional";} ?></td>
<td><a href="<?php echo $this->url(array('controller'=>'admin','action'=>'viewuser'));?>/userId/<?php echo $user['user_id']; ?>"><image src="<?php echo $this->baseUrl();?>/public/images/view.jpg" /></a></td>
<td><a href="<?php echo $this->url(array('controller'=>'admin','action'=>'userstatistics'));?>/userId/<?php echo $user['user_id']; ?>">Workout Statistics</a></td></tr>
<?php 

$i=$i+1;
} ?>

</table>



</div>