
<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addmuscles'), $name = null, $reset = true);?>">Add Muscle</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listmuscles'), $name = null, $reset = true);?>">List Muscles</a>
                                        


</p>
                                        
</div>