<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addpage'), $name = null, $reset = true);?>">Add Page</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listpages'), $name = null, $reset = true);?>">List Pages</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listnews'), $name = null, $reset = true);?>">List News</a>
                                        
    <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addnews'), $name = null, $reset = true);?>">Add News</a>
										
	 <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listcategory'), $name = null, $reset = true);?>">List News Category</a>
                                        
    <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addcategory'), $name = null, $reset = true);?>">Add Category</a>									
										
</p>
                                        
</div>