<div class="workout">
<form action="https://authorize.payments-sandbox.amazon.com/pba/paypipeline" method="post">
  <input type="hidden" name="immediateReturn" value="1" >
  <input type="hidden" name="collectShippingAddress" value="0" >
  <input type="hidden" name="signatureVersion" value="2" >
  <input type="hidden" name="signatureMethod" value="HmacSHA256" >
  <input type="hidden" name="accessKey" value="11SEM03K88SD016FS1G2" >
  <input type="hidden" name="referenceId" value="1" >
  <input type="hidden" name="amount" value="USD 2.99" >
  <input type="hidden" name="signature" value="tqRa7OleaZuiGbnQf8kZfALZIaw0ZXE6r65hvHbVZic=" >
  <input type="hidden" name="isDonationWidget" value="0" >
  <input type="hidden" name="description" value="video" >
  <input type="hidden" name="amazonPaymentsAccountId" value="ETMZFZUTHMJC7MAZPIFL9VFTN1X7K3QLB4Q8H3" >
  <input type="hidden" name="ipnUrl" value="http://fitness.bridge-delivery.com/ipn.php" >
  <input type="hidden" name="returnUrl" value="http://fitness.bridge-delivery.com/amazon_ipn/ipn.php" >
  <input type="hidden" name="processImmediate" value="1" >
  <input type="hidden" name="cobrandingStyle" value="logo" >
  <input type="hidden" name="abandonUrl" value="http://fitness.bridge-delivery.com" >
  <input type="image" src="http://g-ecx.images-amazon.com/images/G/01/asp/golden_small_paynow_withmsg_whitebg.gif" border="0">
</form>



subscription method

<form action="https://authorize.payments-sandbox.amazon.com/pba/paypipeline" method="post">
  <input type="hidden" name="immediateReturn" value="1" >
  <input type="hidden" name="collectShippingAddress" value="0" >
  <input type="hidden" name="signatureVersion" value="2" >
  <input type="hidden" name="signatureMethod" value="HmacSHA256" >
  <input type="hidden" name="accessKey" value="11SEM03K88SD016FS1G2" >
  <input type="hidden" name="recurringFrequency" value="1 month" >
  <input type="hidden" name="amount" value="USD 2.99" >
  <input type="hidden" name="signature" value="4gW7N73AnSmCkI/+eY/A0CVhRDyYys6zNGusCZ1KdEg=" >
  <input type="hidden" name="description" value="fitness4me" >
  <input type="hidden" name="amazonPaymentsAccountId" value="ETMZFZUTHMJC7MAZPIFL9VFTN1X7K3QLB4Q8H3" >
  <input type="hidden" name="ipnUrl" value="http://fitness.bridge-delivery.com/amazon_ipn/ipn.php" >
  <input type="hidden" name="returnUrl" value="http://fitness.bridge-delivery.com/amazon_ipn/ipn.php" >
  <input type="hidden" name="processImmediate" value="0" >
  <input type="hidden" name="cobrandingStyle" value="logo" >
  <input type="hidden" name="abandonUrl" value="http://fitness.bridge-delivery.com/" >
  <input type="image" src="http://g-ecx.images-amazon.com/images/G/01/asp/golden_small_paynow_withmsg_whitebg.gif" border="0">
</form>
</div>