
<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addplan'), $name = null, $reset = true);?>">Add Plan</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listplans'), $name = null, $reset = true);?>">List Plans</a>
                                        


</p>
                                        
</div>