
<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addrates'), $name = null, $reset = true);?>">Add Workout rate</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listworkoutrates'), $name = null, $reset = true);?>">List rates</a>
                                        


</p>
                                        
</div>