
<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addtarget'), $name = null, $reset = true);?>">Add Target</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listtargets'), $name = null, $reset = true);?>">List Targets</a>
                                        


</p>
                                        
</div>