
<div id="sidebar">
<p>

     
                                        
      
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listusers'), $name = null, $reset = true);?>">List Users</a>                                   
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'userstats'), $name = null, $reset = true);?>">User Statistics</a>
                                        


</p>
                                        
</div>