
<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addworkout'), $name = null, $reset = true);?>">Add Exercise</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listworkout'), $name = null, $reset = true);?>">List Exercises</a>
										
	<a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listworkout'), $name = null, $reset = true);?>/active/1">List Active Exercises</a>
                                        


</p>
                                        
</div>