
<div id="sidebar">
<p>

     
                                        
      <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'addwork'), $name = null, $reset = true);?>">Add workout</a>
                                        
     <a href="<?php echo $this->url(array('controller'=>'admin',
                                        'action'=>'listworks'), $name = null, $reset = true);?>">List workouts</a>
                                        


</p>
                                        
</div>