<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
                        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
    <meta charset="utf-8">
        <meta equiv="Content-Type" content="text/html;charset=utf-8" />
        <title><?php echo $this->escape($this->title);?></title>
        <link rel="stylesheet" type="text/css" media="screen"
              href="<?php echo $this->baseUrl();?>/public/css/site.css" />
        <!-- Style CSS -->
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/css/grid/main.css" />

<!-- Google Font -->
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Mate+SC' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Marvel' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Pinyon+Script' rel='stylesheet'>
<link href='http://fonts.googleapis.com/css?family=Cabin:400italic' rel='stylesheet'>
<link rel=stylesheet href="<?php echo $this->baseUrl();?>/public/tinybox/style.css">
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/public/datepicker/jsDatePick_ltr.min.css" />

<script src="http://jqueryjs.googlecode.com/files/jquery-1.3.2.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl();?>/public/tinybox/js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
<script src="https://github.com/fryn/html5slider/raw/master/html5slider.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/public/datepicker/jsDatePick.min.1.3.js"></script>

<style>
input[type=range]:first-of-type {
  width: 200px;
}
</style>
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/public/tinybox/css/prettyPhoto.css" type="text/css" media="screen" charset="utf-8" />

        <script language="javascript" src="<?php echo $this->baseUrl();?>/public/js/frontend_validations.js"></script>
        
      
        
       
        
        <!-- JS Theme Style -->
<script>
if (document.layers) { document.write('<link rel=stylesheet href="<?php echo $this->baseUrl();?>/public/css/style/style.css">') } 
else { document.write('<link rel=stylesheet href="<?php echo $this->baseUrl();?>/public/css/style/style.css">') }
if (document.layers) { document.write('<link rel=stylesheet href="<?php echo $this->baseUrl();?>/public/css/color/default.css">') } 
else { document.write('<link rel=stylesheet href="<?php echo $this->baseUrl();?>/public/css/color/default.css">') }
if (document.layers) { document.write('<link rel=stylesheet href="<?php echo $this->baseUrl();?>/public/css/app/supersized.css">') } 
else { document.write('<link rel=stylesheet href="<?php echo $this->baseUrl();?>/public/css/app/supersized.css">') }
if (document.layers) { document.write('<link rel=stylesheet href="<?php echo $this->baseUrl();?>/public/css/app/hover_effects.css">') } 
else { document.write('<link rel=stylesheet href="<?php echo $this->baseUrl();?>/public/css/app/hover_effects.css">') }

</script>

        
        <script type="text/javascript">
        
        
var interval = 2.5; // delay between rotating images (in seconds)
var random_display = 1; // 0 = no, 1 = yes
interval *= 1000;

var image_index = 0;
image_list = new Array();
image_list[image_index++] = new imageItem("<?php echo $this->baseUrl();?>/public/images/image1.jpg");
image_list[image_index++] = new imageItem("<?php echo $this->baseUrl();?>/public/images/image2.jpg");
image_list[image_index++] = new imageItem("<?php echo $this->baseUrl();?>/public/images/image3.jpg");

var number_of_image = image_list.length;
function imageItem(image_location) {
    this.image_item = new Image();
    this.image_item.src = image_location;
}
function get_ImageItemLocation(imageObj) {
    return(imageObj.image_item.src)
}
function generate(x, y) {
    var range = y - x + 1;
    return Math.floor(Math.random() * range) + x;
}
function getNextImage() {
    if (random_display) {
        image_index = generate(0, number_of_image-1);
    } else {
        image_index = (image_index+1) % number_of_image;
    }
    var new_image = get_ImageItemLocation(image_list[image_index]);
    return(new_image);
}
function rotateImage(place) {
    var new_image = getNextImage();
    document.getElementById('header_image').src = new_image;
    var recur_call = "rotateImage('"+place+"')";
    setTimeout(recur_call, interval);
}
        </script>
    </head>

<body OnLoad="rotateImage()">
<?php 
//get the current action and controller to redifrcet after language change

 $currentPage        =  Zend_Controller_Front::getInstance()->getRequest()->getActionName(); 
 $currentController  =  Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
 
 ?>
<!-- Container Start-->
<div class="container_16" style="padding-left:15px;">
 <div id="topdot" class="grid_16 margin"></div>
    
    <!-- Top Menu -->
    <div class="grid_16 margin">
      <div id="topmenu">
      	<a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'setlanguage'), $name = null, $reset = true);?>/lang/en/page/<?php echo $currentPage; ?>/contr/<?php echo $currentController; ?>"><image src="<?php echo $this->baseUrl();?>/public/images/languages/en.png" /></a><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'setlanguage'), $name = null, $reset = true);?>/lang/de/page/<?php echo $currentPage; ?>/contr/<?php echo $currentController; ?>"><image src="<?php echo $this->baseUrl();?>/public/images/languages/de.png" /></a>
        <!-- Popup Contact Form -->
        <div  class="dnone">
          <div id="contactline" class="popupcontact">
              <h1>Contact Form</h1>
              <form>
              <fieldset><input name="Name" type="text" value="Name:" onfocus="if(this.value=='Name:')this.value='';" onblur=	"if(this.value=='')this.value='Name:';"/></fieldset>  
              <fieldset><input name="Mail" type="text" value="E-Mail:" onfocus="if(this.value=='E-Mail:')this.value='';" onblur=	"if(this.value=='')this.value='E-Mail:';"/></fieldset>
              <fieldset><input name="Web" type="text" value="Web:" onfocus="if(this.value=='Web:')this.value='';" onblur=	"if(this.value=='')this.value='Web:';"/></fieldset>
              <fieldset><textarea name="Message" onfocus="if(this.value=='Message:')this.value='';" onblur=	"if(this.value=='')this.value='Message:';">Message:</textarea></fieldset>
              <fieldset><input type="submit" value="Send" /></fieldset>
              </form>
          </div>
		</div>
        <!-- Popup Contact Adress -->
        <div  class="dnone">
          <div id="contactadress" class="popupcontact">
              <h1>City Adress Detail</h1>
              <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
              <h5>Telephone:</h5>
              <p>(+90) 555 444 333 PBX </p>
              <h5>Fax:</h5>
              <p>(+90) 555 444 333 PBX </p>
              <h5>E-Mail:</h5>
              <p>johndo@domain.com</p>
          </div>
		</div>
      </div>
    </div>

 
  <!-- Navigation Start-->
    <div id="navigation" class="grid_16 margin">
        
        <!-- #Logo-->
        <div class="grid_4 logo margin">
        	<a href="#"><img src="<?php echo $this->baseUrl();?>/public/image/theme/logo.png" alt=""></a>
        </div>
        
        <!-- #Menu-->
        <div class="grid_12 topmenu">
        	<ul id="menu">
               <li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'home'), $name = null, $reset = true);?>">what can we do for you</a></li>
				<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'workhow'), $name = null, $reset = true);?>">How does it work?</a></li>
				<li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'faq'), $name = null, $reset = true);?>">FAQ's</a></li>
                <li><?php if($this->loginStatus == 1){?><a href="<?php echo $this->url(array('controller'=>'user',
                                        'action'=>'listworkouts'), $name = null, $reset = true);?>">Workouts's</a><?php } ?> </li>
                                       
                <li><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'contactpage'), $name = null, $reset = true);?>">Contact Us</a></li>                       
            </ul>
        </div>        
    </div>
    
     <!-- #Page Back -->
    <div id="pageback"></div>
    <div id="tabback2"></div>
    
   
    <div class="grid_16 margin">
    	<div id="tabmenuback2"></div>
        <div class="bigtitle">
        	Fitness4me
        </div>
    </div>
    
    <!-- Clear -->
    <div class="clear margin5"></div>
    
 <div class="grid_11 blog-list margin">
      
        <div class="bloglisting2">
	         <h1><?php echo $this->escape($this->title);?></h1>
	         </div>
	         
	           <!-- Clear -->
    	<div class="clear"></div>
    
        <div class="single-post">
            <?php echo $this->layout()->content; ?>
            
            </div>
          </div>
		<div class="grid_5 margin7">
        
        <!-- #1 -->
        <div class="sidebar-categories">
		
		<?php if($this->loginStatus == 1){?>

<p><a href="<?php echo $this->url(array('controller'=>'user',
                                        'action'=>'logout'), $name = null, $reset = true);?>">Logout</a></p>
<p><a href="<?php echo $this->url(array('controller'=>'user',
                                        'action'=>'settings'), $name = null, $reset = true);?>">Settings</a></p>
<?php }else{ ?>

<p><a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'login'));?>">Login</a> | <a href="<?php echo $this->url(array('controller'=>'index',
                                        'action'=>'registeruser'), $name = null, $reset = true);?>">Register</a></p>
                                        <?php } ?>
		<?php if($this->loginStatus != 1){echo $this->loginForm();echo "<br/><a href='".$this->url(array('controller'=>'index',
                                        'action'=>'forgotlogin'), $name = null, $reset = true)."'>".$this->translate("Forgot password")."?</a>"; }
		
 ?>

<p><?php 
if(($this->loginStatus == 1) )
echo $this->render('user/viewstats.phtml') ; ?></p>
  </div>
    </div>

  <!-- Clear-->
	<div class="clear"></div> 
    
</div>
		
<!-- Clear-->
<div class="clear"></div>     

<!-- Footer 1 Start -->    
<div id="footer1-back">
    <div class="container_16">
      <div class="grid_16 margin">
           <!-- Widget Categories-->
           <div class="footercategories margin">
              <h2>Blog or Page CategorIes</h2>
              <p>Lorem Ipsum is simply dummy text of the printing </p>
              <ul>
                  <li><a href="#">Portfolio</a></li>
                  <li><a href="#">Company News</a></li>
                  <li><a href="#">Services Options</a></li>
                  <li><a href="#">Team Blog</a></li>
                  <li><a href="#">Who Are We</a></li>
                  <li><a href="#">People Says</a></li>
                  <li><a href="#">Contact</a></li>
              </ul>
           </div>
           <!-- Latest Portfolio -->
           <div class="footerportfolio margin">
              <h2>Latest PortfolIo Items</h2>
              <p>Lorem Ipsum is simply dummy text of the printing </p>
            
              <div class="footerportfolio-button"><a href="#" class="middlebutton">Portfolio</a></div>
           </div>
           <!-- Social Widget -->
          
      </div>
    </div>
</div>

<!-- Clear-->
<div class="clear"></div>

<!-- Footer 2 Start -->       
<div id="footer2-back">
	<div class="container_16">
    	<div class="grid_16 footerregister margin">
        	<p>Copright © 2012 City Themes iamthemes.com. All rights reserved. W3C standart web site valid xhtml and css</p><p>Design by Mithat Sigmaz / <a href="http://www.cubegraphic.net">CUBE GRAPHIC</a> - Code by IAMILKAY / <a href="http://www.iamthemes.com">IAMTHEMES</a></p>
        </div>
    </div>
</div>
<script type="text/javascript" charset="utf-8">
jQuery.noConflict();
  jQuery(document).ready(function(){
    jQuery("a[rel^='prettyPhoto']").prettyPhoto({slideshow:false,gallery_markup:'',custom_markup:'',markup: '<div class="pp_pic_holder"> \
						<div class="ppt">&nbsp;</div> \
						<div class="pp_top"> \
							<div class="pp_left"></div> \
							<div class="pp_middle"></div> \
							<div class="pp_right"></div> \
						</div> \
						<div class="pp_content_container"> \
							<div class="pp_left"> \
							<div class="pp_right"> \
								<div class="pp_content"> \
									<div class="pp_loaderIcon"></div> \
									<div class="pp_fade"> \
										<a href="#" class="pp_expand" title="Expand the image">Expand</a> \
										<div class="pp_hoverContainer"> \
											<a class="pp_next" href="#">next</a> \
											<a class="pp_previous" href="#">previous</a> \
										</div> \
										<div id="pp_full_res"></div> \
										<div class="pp_details"> \
											 \
											<p class="pp_description"></p> \
											{pp_social} \
											 <a class="pp_close" href="#">Close</a> \
										</div> \
									</div> \
								</div> \
							</div> \
							</div> \
						</div> \
						<div class="pp_bottom"> \
							<div class="pp_left"></div> \
							<div class="pp_middle"></div> \
							<div class="pp_right"></div> \
						</div> \
					</div> \
					<div class="pp_overlay"></div>'});
  });
</script>

</body>
</html>
<script type="text/javascript">
	window.onload = function(){
		new JsDatePick({
			useMode:2,
			target:"inputField",
			dateFormat:"%d-%m-%Y"
			
		});
	};
</script>